// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Paste struct {
	ID                string
	UserID            sql.NullInt64
	Title             string
	Body              string
	EncryptedPasteKey string
	CreatedAt         sql.NullTime
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      sql.NullBool
	CreatedAt    sql.NullTime
}
