// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Paste struct {
	ID                string
	UserID            sql.NullInt64
	Title             string
	Body              string
	EncryptedPasteKey string
	CreatedAt         time.Time
}

type Session struct {
	ID        string
	UserID    int64
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    time.Time
}
