// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, is_admin)
VALUES (?, ?, ?, ?)
RETURNING id, username, email, password_hash, is_admin, created_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, is_admin, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, username, email, password_hash, is_admin, created_at FROM users WHERE email = ?1 OR username = ?1 LIMIT 1
`

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, identifier string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailOrUsername, identifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
